// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NothingToForgetBot.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NothingToForgetBot.Data.Migrations
{
    [DbContext(typeof(NothingToForgetBotContext))]
    partial class NothingToForgetBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NothingToForgetBot.Data.Languages.Models.ChatWithLanguageDbModel", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChatId"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.HasKey("ChatId")
                        .HasName("pk_chat_with_language");

                    b.ToTable("chats_with_language", (string)null);
                });

            modelBuilder.Entity("NothingToForgetBot.Data.Languages.Models.LanguageDbModel", b =>
                {
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ToTable("supported_languages", (string)null);
                });

            modelBuilder.Entity("NothingToForgetBot.Data.Messages.Models.RepeatedViaMinutesMessageDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval");

                    b.HasKey("Id")
                        .HasName("pk_repeated_via_minutes_message");

                    b.ToTable("repeated_via_minutes_messages", (string)null);
                });

            modelBuilder.Entity("NothingToForgetBot.Data.Messages.Models.RepeatedViaSecondsMessageDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval");

                    b.HasKey("Id")
                        .HasName("pk_repeated_via_seconds_message");

                    b.ToTable("repeated_via_seconds_messages", (string)null);
                });

            modelBuilder.Entity("NothingToForgetBot.Data.Messages.Models.ScheduledMessageDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("PublishingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publishing_date");

                    b.HasKey("Id")
                        .HasName("pk_scheduled_message");

                    b.ToTable("scheduled_messages", (string)null);
                });

            modelBuilder.Entity("NothingToForgetBot.Data.Notes.Models.NoteDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.HasKey("Id")
                        .HasName("pk_note");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("NothingToForgetBot.Data.TimeZones.Models.ChatTimeZoneDbModel", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChatId"));

                    b.Property<int>("TimeZone")
                        .HasColumnType("integer")
                        .HasColumnName("time_zone");

                    b.HasKey("ChatId")
                        .HasName("pk_chat_time_zone");

                    b.ToTable("chat_time_zones", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
